// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: wsc/protocodec/frame.proto

package protocodec

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Frame 是 protobuf codec 使用的二进制 wire 信封, 与 JSON 的 Message 信封一一对应:
// id 用于请求/响应匹配, heart 是心跳标志, data 承载序列化后的载荷 (载荷本身也是
// 一个 proto.Message), has_data 区分 nil payload 与序列化后为空字节的合法 payload。
type Frame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Heart         bool                   `protobuf:"varint,3,opt,name=heart,proto3" json:"heart,omitempty"`
	HasData       bool                   `protobuf:"varint,4,opt,name=has_data,json=hasData,proto3" json:"has_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_wsc_protocodec_frame_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_wsc_protocodec_frame_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_wsc_protocodec_frame_proto_rawDescGZIP(), []int{0}
}

func (x *Frame) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Frame) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Frame) GetHeart() bool {
	if x != nil {
		return x.Heart
	}
	return false
}

func (x *Frame) GetHasData() bool {
	if x != nil {
		return x.HasData
	}
	return false
}

var File_wsc_protocodec_frame_proto protoreflect.FileDescriptor

const file_wsc_protocodec_frame_proto_rawDesc = "" +
	"\n" +
	"\x1awsc/protocodec/frame.proto\x12\x03wsc\"\\\n" +
	"\x05Frame\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x14\n" +
	"\x05heart\x18\x03 \x01(\bR\x05heart\x12\x19\n" +
	"\bhas_data\x18\x04 \x01(\bR\ahasDataB)Z'github.com/zdypro888/net/wsc/protocodecb\x06proto3"

var (
	file_wsc_protocodec_frame_proto_rawDescOnce sync.Once
	file_wsc_protocodec_frame_proto_rawDescData []byte
)

func file_wsc_protocodec_frame_proto_rawDescGZIP() []byte {
	file_wsc_protocodec_frame_proto_rawDescOnce.Do(func() {
		file_wsc_protocodec_frame_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wsc_protocodec_frame_proto_rawDesc), len(file_wsc_protocodec_frame_proto_rawDesc)))
	})
	return file_wsc_protocodec_frame_proto_rawDescData
}

var file_wsc_protocodec_frame_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_wsc_protocodec_frame_proto_goTypes = []any{
	(*Frame)(nil), // 0: wsc.Frame
}
var file_wsc_protocodec_frame_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_wsc_protocodec_frame_proto_init() }
func file_wsc_protocodec_frame_proto_init() {
	if File_wsc_protocodec_frame_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wsc_protocodec_frame_proto_rawDesc), len(file_wsc_protocodec_frame_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wsc_protocodec_frame_proto_goTypes,
		DependencyIndexes: file_wsc_protocodec_frame_proto_depIdxs,
		MessageInfos:      file_wsc_protocodec_frame_proto_msgTypes,
	}.Build()
	File_wsc_protocodec_frame_proto = out.File
	file_wsc_protocodec_frame_proto_goTypes = nil
	file_wsc_protocodec_frame_proto_depIdxs = nil
}
